// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"1":{"path":"/datacenter","name":"数据中心","icon":"smile","file":"@/pages/DataCenter/index.tsx","parentId":"ant-design-pro-layout","id":"1"},"2":{"path":"/user","layout":false,"id":"2"},"3":{"name":"login","path":"/user/login","file":"@/pages/User/Login/index.tsx","parentId":"2","id":"3"},"4":{"file":"@/pages/404.tsx","parentId":"2","id":"4"},"5":{"path":"/admin","name":"admin","icon":"crown","access":"canAdmin","parentId":"ant-design-pro-layout","id":"5"},"6":{"path":"/admin/sub-page","name":"sub-page","icon":"smile","file":"@/pages/Welcome.tsx","parentId":"5","id":"6"},"7":{"file":"@/pages/404.tsx","parentId":"5","id":"7"},"8":{"name":"list.table-list","icon":"table","path":"/list","file":"@/pages/TableList/index.tsx","parentId":"ant-design-pro-layout","id":"8"},"9":{"path":"/","redirect":"/datacenter","parentId":"ant-design-pro-layout","id":"9"},"10":{"file":"@/pages/404.tsx","parentId":"ant-design-pro-layout","id":"10"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","file":"@/.umi/plugin-layout/Layout.tsx","isLayout":true},"umi/plugin/openapi":{"path":"/umi/plugin/openapi","id":"umi/plugin/openapi","file":"/Users/zhongmei/Desktop/my-file/go/easylake/front/src/.umi/plugin-openapi/openapi.tsx"}},
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__DataCenter__index" */'@/pages/DataCenter/index.tsx')),
'2': React.lazy(() => import( './EmptyRoute')),
'3': React.lazy(() => import(/* webpackChunkName: "p__User__Login__index" */'@/pages/User/Login/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'5': React.lazy(() => import( './EmptyRoute')),
'6': React.lazy(() => import(/* webpackChunkName: "p__Welcome" */'@/pages/Welcome.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__TableList__index" */'@/pages/TableList/index.tsx')),
'9': React.lazy(() => import( './EmptyRoute')),
'10': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: ".umi__plugin-layout__Layout" */'@/.umi/plugin-layout/Layout.tsx')),
'umi/plugin/openapi': React.lazy(() => import(/* webpackChunkName: ".umi__plugin-openapi__openapi" */'/Users/zhongmei/Desktop/my-file/go/easylake/front/src/.umi/plugin-openapi/openapi.tsx')),
},
  };
}
