// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from '/Users/zhongmei/Desktop/my-file/go/easylake/front/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import CrownOutlined from '/Users/zhongmei/Desktop/my-file/go/easylake/front/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import TableOutlined from '/Users/zhongmei/Desktop/my-file/go/easylake/front/node_modules/@ant-design/icons/es/icons/TableOutlined';
export default { SmileOutlined, CrownOutlined, TableOutlined };
